### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#64] opened 2017-02-24 22:17 UTC
![capture](https://cloud.githubusercontent.com/assets/15007183/23323113/2b50ab04-fab5-11e6-8ac1-3d5cf96b58df.PNG)

**Comment by X01X012013** [comment] 2017-02-24 22:27
I can't reproduce this. We have a fix inherited from AAK: 
```
@@||$xmlhttprequest,domain=last.fm
@@||adsensecustomsearchads.com/adsense/$script,domain=last.fm
@@||securepubads.g.doubleclick.net$script,domain=last.fm
```
Can you check your end? And please give a more specific link if you are still having issues.

**Comment by xxcriticxx** [comment] 2017-02-24 22:33
i get that msg on main page let me try filters

**Comment by X01X012013** [comment] 2017-02-24 22:35
Well, I'm not getting anything... 
![image](https://cloud.githubusercontent.com/assets/7283682/23323678/e044afc4-faa6-11e6-8c7c-f0044e3d7879.png)

**Comment by xxcriticxx** [comment] 2017-02-24 22:37
no go with filters maybe its only for us ip

![capture](https://cloud.githubusercontent.com/assets/15007183/23323725/e2b31082-fab7-11e6-84fa-622df1d6383b.PNG)

**Comment by X01X012013** [comment] 2017-02-24 22:40
I'm not seeing anything... What's your setup? 
![image](https://cloud.githubusercontent.com/assets/7283682/23323770/5398855e-faa7-11e6-84b9-28ef36761fb3.png)

**Comment by xxcriticxx** [comment] 2017-02-24 22:41
ff 51.0.1 + ublock o + your script

**Comment by X01X012013** [comment] 2017-02-24 23:04
Nope, still nothing with FireFox. 
![image](https://cloud.githubusercontent.com/assets/7283682/23324424/f0cfaeee-faaa-11e6-90c1-37fcd7972153.png)

**Comment by uBlock-user** [comment] 2017-02-25 07:46
Last.fm has already been patched by uBO. Force update all your uBO filters and try again.

**Comment by xxcriticxx** [comment] 2017-02-25 13:59
i reset all settings in ubo and pulled only default lists. in chrome reset it do default settings and clear browsing history and cookies. today am not on my host system and i still get msg about ad block.

**Comment by X01X012013** [comment] 2017-02-25 14:33
Yes, it should been fixed by Easy List. Do you have custom filters?

**Comment by xxcriticxx** [comment] 2017-02-25 15:02
nope all stock filters only

**Comment by X01X012013** [comment] 2017-02-25 20:31
Let's handle this in #67

**Closed by X01X012013** 2017-02-25 20:31 UTC
Labels: Cannot Reproduce
