### ISSUE TITLE
mooseroots.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#96] opened 2017-03-16 11:14 UTC
http://names.mooseroots.com/

Scroll down the page a bit and the overlay will appear.

**Comment by xxcriticxx** [comment] 2017-03-16 13:23
i can’t reproduce the issue

**Comment by uBlock-user** [comment] 2017-03-16 13:32
That's probably because you must a white-listing filter for an XHR from the domain.

**Comment by X01X012013** [comment] 2017-03-16 13:33
OK, I'll have a look.

**Comment by uBlock-user** [comment] 2017-03-16 13:36
This is how it looks like - https://i.gyazo.com/a3de0b9b15996658905839cfaccd540e.png

**Comment by X01X012013** [comment] 2017-03-16 15:09
Fixed with important style. Added to Script.

**Comment by uBlock-user** [comment] 2017-03-16 15:16
Works Perfectly! There are few domains which also run the same script. One of them is `insidegov.com`,  I will list more as I come across.

**Comment by X01X012013** [comment] 2017-03-16 15:32
OK, added to Script.

**Comment by uBlock-user** [comment] 2017-03-16 17:01
You may close the issue though.

**Closed** 2017-03-16 17:21 UTC
Labels: Fixed

**Comment by uBlock-user** [comment] 2017-07-25 07:33
List - https://github.com/uBlockOrigin/uAssets/issues/573

**Comment by jspenguin2017** [comment] 2017-07-25 14:21
Since it is taken care of by uBlock filter, I'll just remove the script rule...
