### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#84] opened 2017-03-03 21:29 UTC
only me with ad block on this page?

http://fotoblogia.pl/10356,world-press-photo-2017-czy-mamy-do-czynienia-z-kolejnym-oszustwem-i-ustawianym-fotoreportazem

**Comment by X01X012013** [comment] 2017-03-03 22:06
This is fixed by List 6.27 and Script 6.73.

**Comment by uBlock-user** [comment] 2017-03-04 07:30
Not fixed, I can reproduce it.

**Comment by uBlock-user** [comment] 2017-03-04 07:38
This should kill it for the time being - `fotoblogia.pl##script:inject(overlay-buster.js)`

**Comment by X01X012013** [comment] 2017-03-04 14:58
Did you update List? I added a generic rule `###like-us-adblock-modal`.

**Comment by uBlock-user** [comment] 2017-03-04 15:14
I only use UserScript and not the List. I thought you patched in the UserScript. Nevermind.

**Comment by X01X012013** [comment] 2017-03-05 16:17
Looks like this is good, I'll close this issue now.

**Closed by X01X012013** 2017-03-05 16:17 UTC
Labels: Fixed
