### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by Ntweat** [X01X012013/AdBlockProtector#3] opened 2016-07-31 00:15 UTC
Ndtv has started blocking again

**Comment by X01X012013** [comment] 2016-07-31 23:21
Hi there, I cannot reproduce the issue. 
![screenshot](http://i.imgur.com/bEB81Ti.png)
Can you tell me which browser you are using along with your AdBlocker, script host, and installed script list? If you have a specific link, that will help too.

**Comment by Ntweat** [comment] 2016-07-31 23:33
Here you go...

Chrome + ABP + Tamper Monkey 

<img width="1440" alt="screen shot 2016-07-31 at 7 32 01 pm" src="https://cloud.githubusercontent.com/assets/1205924/17280086/7ef12eb8-5755-11e6-8c42-d5b3c39c52a3.png">

**Comment by X01X012013** [comment] 2016-07-31 23:45
Hi there, I will need the link and your script list as well. Could you provide these information?

**Comment by Ntweat** [comment] 2016-07-31 23:49
Any link

I think I am blocking taboola.com ads also via a personal filter. 

`@@||ndtv.com^*/taboola*/*/*`

http://www.ndtv.com/india-news/defence-minister-manohar-parrikar-under-congress-attack-after-jibe-at-aamir-khan-1438423?pfrom=home-lateststories

<img width="1440" alt="screen shot 2016-07-31 at 7 47 48 pm" src="https://cloud.githubusercontent.com/assets/1205924/17280192/dc90273e-5757-11e6-9bfa-f6c8db0cccd9.png">

**Comment by X01X012013** [comment] 2016-08-01 00:20
Fixed in 1.0.55 :smile: Let me know if there are other issues. 

Lock "getNoTopLatestNews" to an empty function.

**Comment by Ntweat** [comment] 2016-08-01 00:23
Thanks.. Works now 👍  
I bet all indian media houses are keep track of reek at least.

**Comment by X01X012013** [comment] 2016-08-01 01:16
Reek updates Aak once a month, but I do it whenever it is needed, sometimes even a few times per day. This won't go well for large project like Aak since it is much harder to test that. 
Since this issue is fixed, I'll close this issue. Let me know if there are other issues.

**Closed by X01X012013** 2016-08-01 01:16 UTC
