### ISSUE TITLE
tvregionalna24.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#41] opened 2017-01-28 16:44 UTC
please see https://github.com/MajkiIT/polish-ads-filter/issues/2080

page started to use 15 sec ads before all videos looking for script to remove advertisement

test on:

http://www.tvregionalna24.pl/aktualnosci/12760,jagiellonska-w-malborku-juz-przejezdna-27012017

**Comment by X01X012013** [comment] 2017-01-28 19:07
I can't understand what is said in that issue. 

If someone found out how to grab the video link, please let me know. I'm a little bit busy these days, I'll have a look at it later...

**Comment by xxcriticxx** [comment] 2017-01-28 19:36
Read description above page shows 15 sec ad before video now looking for script to remove it

**Comment by X01X012013** [comment] 2017-01-28 19:40
@xxcriticxx I know that, but what other guys in that issue said? Can you translate these posts? 
![image](https://cloud.githubusercontent.com/assets/7283682/22399297/e0dcfdc0-e556-11e6-9d4f-68c5e2970e38.png)

**Comment by xxcriticxx** [comment] 2017-01-28 20:52
@MajkiIT said that use to be layer with ads and vid now he doesn't see it 

@F4z thinks that we have to use script here to bypass ads. if you block ads with filters vid displays error. videos are from youtube on this website. doesnt have any ideas right now how to bypass this using adblock/ublock leave it open maybe someone else will come up with something. 

and then i posted it here :)

**Comment by X01X012013** [comment] 2017-01-28 21:16
@xxcriticxx Ah, do we know how to grab the YouTube link yet? If we have that it's one line of code.

**Comment by F4z** [comment] 2017-01-28 21:19
@X01X012013  I think they use this script to load a YouTube vidoe/player - http://wklej.org/id/3029841/txt/
For example for first video here - http://www.tvregionalna24.pl/aktualnosci/12760,jagiellonska-w-malborku-juz-przejezdna-27012017
`$(".video_outer[data-id=7676]").html('<div class="embed-responsive embed-responsive-16by9"><iframe width="750" height="422" class="embed-responsive-item" src="//www.youtube.com/embed/ia6A9O7Bw6U?showinfo=0&amp;autoplay=0" frameborder="0" allowfullscreen></iframe></div>');`

**Comment by X01X012013** [comment] 2017-01-28 22:36
@F4z Ah, interesting... Is requesting the JS the only way to get the YouTube URL?

**Comment by F4z** [comment] 2017-01-29 00:55
@X01X012013 sorry, but I do not know to much about JavaScript, so I do not know the answer to your question.

**Comment by xxcriticxx** [comment] 2017-01-29 01:08
what happens if we switch this `var advert_duration = 15;` to `= 0` ???

**Comment by X01X012013** [comment] 2017-01-29 01:23
@F4z @xxcriticxx I think that would crash their whole script. How about put in our own `videojs()`?

**Comment by X01X012013** [comment] 2017-01-29 02:27
Hi, this website is fixed in Script 3.0.15. Try it out and let me know how it goes. I only tested it on the test page above.

**Comment by xxcriticxx** [comment] 2017-01-29 02:40
then set it to 1 second only

**Comment by X01X012013** [comment] 2017-01-29 02:55
@xxcriticxx To enforce the value to the variable, I need to set it as read-only, which might crash their script when it tries to initialize the variable again. I already found another solution, why don't you check it out!

**Comment by xxcriticxx** [comment] 2017-01-29 03:15
sure just came back from computer crash give me 5 min

**Comment by xxcriticxx** [comment] 2017-01-29 03:23
@X01X012013 works!

**Comment by X01X012013** [comment] 2017-01-29 03:25
Alright, I'll close this issue now.

**Comment by MajkiIT** [comment] 2017-01-29 08:31
After I add this JS i have problem with YT. I can't start any video. 
![ublock_today](https://cloud.githubusercontent.com/assets/11302675/22402854/a6153068-e605-11e6-8593-a4ab757bb16f.png)

**Comment by X01X012013** [comment] 2017-01-29 12:12
@MajkiIT Hi, I could not reproduce this issue, is your setup officially supported?

**Comment by xxcriticxx** [comment] 2017-01-29 12:16
@MajkiIT only works on chrome or opera

@X01X012013 firefox support a must have!

**Comment by X01X012013** [comment] 2017-01-29 12:21
@xxcriticxx It works on my Firefox.

**Comment by xxcriticxx** [comment] 2017-01-29 12:23
i get same errors like @MajkiIT cant use youtube or github

**Comment by MajkiIT** [comment] 2017-01-29 13:31
@X01X012013 I tested yours script on 2 PC with different systems and on Firefox I have the same problem.

**Comment by X01X012013** [comment] 2017-01-29 13:48
@MajkiIT @xxcriticxx 
It looks like Greasemonkey could not get over the restriction set by Firefox. 
https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/
I'll see if there is a workaround.

**Comment by X01X012013** [comment] 2017-01-29 14:22
@MajkiIT @xxcriticxx 
I will try to make a dropper as a workaround, I'll update this post with results.

**Comment by xxcriticxx** [comment] 2017-01-29 14:32
thx for help i will test when ready

**Comment by xxcriticxx** [comment] 2017-01-29 14:33
can you reopen this issue or start new one?

**Comment by X01X012013** [comment] 2017-01-29 15:05
This dropper definitely works, but somehow when put into a Userscript, it does nothing. It works just fine in console. Greasemonkey is a mess, can you guys just switch to Tampermonkey? 
```JavaScript
//Set variable
var unsafeWindow = window;
//Load script
var request = new XMLHttpRequest();
request.open('GET', 'https://x01x012013.github.io/AdBlockProtector/AdBlockProtector.user.js', false);
request.send(null);
//Check load state and drop script
if (request.status === 200) {
    eval(request.responseText);
} else {
    alert("Could not load AdBlock Protector. ");
}
```

**Comment by X01X012013** [comment] 2017-01-29 15:58
@xxcriticxx @MajkiIT 
OK, I made a dropper, it seems to work in Greasemonkey in Firefox. 
Uninstall the old script and install this one: https://x01x012013.github.io/AdBlockProtector/AdBlockProtector.Dropper.user.js
I don't guarantee that this will work, but it worked on my machine.

**Comment by MajkiIT** [comment] 2017-01-29 16:04
@X01X012013 On my computers are working. Thanks for your help. You are genius.

**Comment by X01X012013** [comment] 2017-01-29 16:05
Alright, i'll close this issue now.

**Closed by X01X012013** 2017-01-29 16:05 UTC
Labels: Fixed

**Comment by xxcriticxx** [comment] 2017-01-29 16:38
I will test in about 30 min not by computer right now

**Comment by xxcriticxx** [comment] 2017-01-29 17:12
works!
