### ISSUE TITLE
tune.pk

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#92] opened 2017-03-11 18:03 UTC
https://tune.pk/video/6978566/geostorm-2017-official-teaser-trailer-1-ft-katheryn-winnick-gerard-butler

![capture](https://cloud.githubusercontent.com/assets/15007183/23825626/1c8e4c46-065b-11e7-9866-6c6b208deac5.PNG)

**Comment by uBlock-user** [comment] 2017-03-11 18:30
Lock `ad_blocker` in the script.

**Comment by X01X012013** [comment] 2017-03-11 19:56
Doesn't work. Let's just block the block screen. `tune.pk###annoy-wrapper`

**Comment by xxcriticxx** [comment] 2017-03-11 19:58
after that you got 10 sec add that you dont see but have to wait

**Comment by uBlock-user** [comment] 2017-03-11 20:14
I cannot reproduce. Most probably patched as `googletag` remains undefined due uBO's experimental filter which breaks the detector I guess.

**Comment by xxcriticxx** [comment] 2017-03-11 20:16
there is 10 sec black screen till the video starts

**Comment by uBlock-user** [comment] 2017-03-11 20:18
add - `||player.tune.pk/v2/js/annoy.min.js^` That one is from Adguard' FilterList, that's why I cannot reproduce.

**Comment by xxcriticxx** [comment] 2017-03-11 20:21
i am still waiting on something in the blakc screen

**Comment by xxcriticxx** [comment] 2017-03-11 20:21
both filters work

**Comment by X01X012013** [comment] 2017-03-11 20:26
If you click the play button on the lower left, the video plays immediately.

**Comment by xxcriticxx** [comment] 2017-03-11 20:27
yep i call this fixed

**Comment by X01X012013** [comment] 2017-03-11 20:29
Good. I'll close this issue now.

**Closed by X01X012013** 2017-03-11 20:29 UTC
Labels: Fixed
