### ISSUE TITLE
wp.pl and related

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#40] opened 2017-01-24 19:01 UTC
website again made couple changes @X01X012013 can you please check

**Comment by X01X012013** [comment] 2017-01-25 04:34
Thank you for your report, I will look into this when I have time.

**Comment by xxcriticxx** [comment] 2017-01-25 16:13
thanks for help

**Comment by X01X012013** [comment] 2017-01-25 18:03
Test URL: 
http://opinie.wp.pl/andrzej-zupanski-ukradl-miliony-zostal-bohaterem-6083990028674177a
http://www.money.pl/gospodarka/wiadomosci/artykul/marki-wlasne-biedronka-lidl-produkty-markowe,55,0,2241335.html

**Comment by xxcriticxx** [comment] 2017-01-25 20:27
@X01X012013 did you release new ver of your software so i can test?

**Comment by X01X012013** [comment] 2017-01-25 20:41
Looks like they put the detector inside the video player. All the functions are closured, pretty well done. If someone figured out how to grab the link to the video file, please let me know. For now, I don't have more tricks in my bag. I'll have another look later when I have time.

**Comment by xxcriticxx** [comment] 2017-01-26 02:24
@mikhoul or @szymon1118 any input on this?

**Comment by szymon1118** [comment] 2017-01-26 11:02
@X01X012013 Link to the video could be grabbed by splitting and trimming (formatting) what is inside `<meta name="keywords" content="` more info here: `http://wp.tv/jsapi/article_related.js`. Then you can access playlist of videos eg. `http://wp.tv/api/article_related.json?tags=marki+w%C5%82asne%3Bbiedronka%3Bsklep%3Bsie%C4%87%3Bproducenci+%C5%BCywno%C5%9Bci&domain=www.money.pl&type=default`. Inside JSON you can get `mid` (probably movie id) and from this point there are two ways to grab video url (first link probably contains urls for whole playlist):

- http://wp.tv/player/related.json?domain=www.money.pl&mid=1996701&type=video

- http://wp.tv/player/mid,1996701,embed.json

**Comment by xxcriticxx** [comment] 2017-01-26 14:59
put still we have to change the player with our own player?

**Comment by X01X012013** [comment] 2017-01-26 15:54
@xxcriticxx Yes, we would need to do that.

**Comment by X01X012013** [comment] 2017-01-26 16:26
@szymon1118 I am able to grab the first JSON, but the `url` array is empty when I try to get `"http://wp.tv/player/mid," + mid + ",embed.json"`. I noticed there are 30 elements in the first JSON, the first one has title matching the video player's title, is that the right one?

**Comment by mikhoul** [comment] 2017-01-26 16:50
Sadly I can't test the video from Canada.

**Comment by szymon1118** [comment] 2017-01-26 17:59
@X01X012013 I have changed your code from:
```javascript
if(mid){
    console.log("http://wp.tv/player/mid," + mid + ",embed.json");
    $.get("http://wp.tv/player/mid," + mid + ",embed.json", function(data){console.log(data);});
}
```
to:
```javascript
if(mid){
    console.log("http://wp.tv/player/mid," + mid + ",embed.json");
    $.get("http://wp.tv/player/mid," + mid + ",embed.json", function(data){
        window.open(data.clip.url[1].url, '_blank').focus();
    });
}
```
and for me it works for both `money.pl` and `opinie.wp.pl` websites so I don't really know where is the problem :smile:. Thanks for your help.

**Comment by X01X012013** [comment] 2017-01-26 18:28
@szymon1118 Hi, that is not the issue there, `url[1]` is undefined for the first test link. I am able to get the first video of each page working, working on others. 
![image](https://cloud.githubusercontent.com/assets/7283682/22344739/7d13fc1e-e3ba-11e6-8f04-481704c66217.png)

**Comment by X01X012013** [comment] 2017-01-26 18:43
Hi guys, I was able to make the first video of some pages working! Please have a look and submit links to pages where the first video is not working. 

@szymon1118 Thanks for your help, I need clarification on something: `article_related.json` contains video in the correct order? So the first video is `clip[0]` and `clip[1]` for the second one? Why is there 30 items in the JSON? I bet there won't be 30 videos on the same page...

**Comment by xxcriticxx** [comment] 2017-01-26 18:50
@X01X012013 what player did you use? looks like you substituted the original player

@mikhoul i am in usa most stuff wont work but some will 

paging @MajkiIT and @F4z to test

**Comment by X01X012013** [comment] 2017-01-26 18:52
@xxcriticxx The browser built-in player, like last time. One thing I need you guys to test is the correct video is loaded. I'm assuming `clips` array is in the correct order...

**Comment by xxcriticxx** [comment] 2017-01-26 20:26
@X01X012013 what do we need script + list? or script only?

**Comment by xxcriticxx** [comment] 2017-01-26 20:29
here is page with multiple video's

`http://wiadomosci.wp.pl/kat,1329,title,Austria-12-latek-czlonkiem-terrorystycznej-siatki-w-Wiedniu,wid,18685214,wiadomosc.html?ticaid=11883e`

**Comment by xxcriticxx** [comment] 2017-01-26 20:36
at this page `http://kobieta.wp.pl/najmodniejsze-fryzury-na-nadchodzacy-sezon-6084375065597057a` correct video plays for second then freezes and new one starts 

correct vid:

![capture](https://cloud.githubusercontent.com/assets/15007183/22349303/1f1dc95a-e3dd-11e6-98eb-8362138b8d44.PNG)

new vid:

![capture2](https://cloud.githubusercontent.com/assets/15007183/22349312/28395234-e3dd-11e6-8017-11aa3ff1f8f1.PNG)

**Comment by X01X012013** [comment] 2017-01-26 23:31
@xxcriticxx 
Hi, both List and Script are updated. The new implementation is moved from List to Script. 

For your reply above, what should be the correct video? Just a black screen?

**Comment by xxcriticxx** [comment] 2017-01-27 00:52
@X01X012013 vid about makeup and hair by title `Najmodniejsze fryzury na nadchodzący sezon` maybe ask @szymon1118 for help

**Comment by X01X012013** [comment] 2017-01-27 04:08
I'm a little bit busy these days, but I promise that I will be back. If someone can sort out how to grab the correct media ID, then I will be back immediately.

**Comment by xxcriticxx** [comment] 2017-01-27 12:07
@X01X012013 i tested this on different computer and correct vid plays maybe was website error or maybe something with the computer i will test so more and report.

**Comment by szymon1118** [comment] 2017-01-27 22:56
@X01X012013 Referring to your question about `clips` array order i think that it is in the correct order. Regarding to 30 videos in JSON i think there is a playlist like on youtube to watch other video thematically related with the first one or something :smile: so it depends on demand for function to load new video (if anyone would like to watch new video and is it worth your time). For me every previously tested video works fine. I found a solution in AAK script to grab `mid` directly from player in website source. Here is the code: `http://pastebin.com/NvrWwKFR`. It is not clean, I know but I had to use `setTimeout` to wait until the `mid` variable will not be `undefined`. According to the playlist using for example this JSON: `http://wp.tv/player/related.json?domain=opinie.wp.pl&mid=1996794&type=video` we can grab if I am not mistaken every related video with the first one so there is no need now to use `keywords`. About Geo Lock problem I have not looked into it yet.

**Comment by X01X012013** [comment] 2017-01-27 23:59
@szymon1118 Wait, I'm now confused, so what is the correct way to grab `mid`? And what to do if there are more than one video on the same page?

**Comment by xxcriticxx** [comment] 2017-01-28 00:05
@X01X012013 the correct way is the way you have it now.

**Comment by xxcriticxx** [comment] 2017-01-29 17:26
@X01X012013 is wp.pl fix in dropper version?

**Comment by X01X012013** [comment] 2017-01-29 17:41
@xxcriticxx All the dropper does is to load the main script, it does not add anything. Currently `wp.pl` is partially fixed, so expect similar behavior with dropper version.

**Comment by xxcriticxx** [comment] 2017-01-29 17:54
@X01X012013 roger

@szymon1118 can you look at geo lock part please?

**Comment by X01X012013** [comment] 2017-02-06 23:43
I'll add multi-video support when I have time. Thank you for your patience.

**Comment by szymon1118** [comment] 2017-02-07 17:40
Sorry for the long absence but I had exams. Studies, you know :smile:.

@xxcriticxx I tested two websites through VPN and i have not any Geolock protection so maybe It could be bypassed by replacing a player. Anyway I hadn't noticed any geo lock myself connecting via VPN. I also found that https://github.com/MajkiIT/polish-ads-filter found a solution: http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/ but I think when WP change their code the script will not work.

@X01X012013 The newest logic of grabbing `mid` I found in AAK code works for every site that @xxcriticxx posted so I think we can stay with this method. The problem is with replacing multiple videos on website. I did some tests and for me it is hard to find a good method to replace many films on single website because eg. there is a website: `http://wiadomosci.wp.pl/kat,1329,title,Austria-12-latek-czlonkiem-terrorystycznej-siatki-w-Wiedniu,wid,18685214,wiadomosc.html?ticaid=11883e` and without scrolling down while loading only one video is loaded.
![image](https://cloud.githubusercontent.com/assets/6980624/22702533/57ab85a4-ed61-11e6-92c7-32357dfaa217.png)

What I observed that they are loading dynamically new articles with videos attached by AJAX while you scrolling down a page. So we should dynamically replace new videos or scroll very fast to the very down of website and then up like I did (I think scrolling down with JS is a bad practice but I hadn't found any better solution). It it my code for now: http://pastebin.com/EQHrRUAb.

**Comment by X01X012013** [comment] 2017-02-07 19:13
@szymon1118 Does that Userscript work? 

I implemented multi-video support to 3.0.20, try it out and let me know how it goes.

**Comment by szymon1118** [comment] 2017-02-07 21:04
@X01X012013 The code I sent works for me but I tested it only in chrome. Userscript works (good job) but the old method with `keywords` is bad in my opinion because the title upper video doesn't match video content (for the first video it is good but for the next video title is different). To my mind the best option I have found till now will be to grab mid directly from the player as I posted in a code above:
`var mid = $( player ).find(".titlecont a.title").attr("href").match(/mid[=,]([0-9]+)/);`

**Comment by X01X012013** [comment] 2017-02-07 22:09
@szymon1118 I mean this one: http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/
Does it work or it's outdated? 

I'll update the mid grabbing method.

**Comment by X01X012013** [comment] 2017-02-07 22:40
@szymon1118 @xxcriticxx 
3.0.21 is out, try it out and let me know if the video are right this time :D

**Comment by szymon1118** [comment] 2017-02-07 23:12
@X01X012013 Great job :smile: It seems to work for every site that had been posted. Regarding to http://www.certyficate.it/pomijanie-wykrywania-adblocka-portalach-wp/ I know that they asked for help on adguard forum: https://forum.adguard.com/index.php?threads/resolved-kobieta-wp-pl.18565/page-2#post-123248 so maybe you can check more informations from here. I tested this script and I remember that I couldn't run it in chrome. Tried in firefox with Greasemonkey and it worked so maybe script has more issues.

**Comment by X01X012013** [comment] 2017-02-07 23:14
@szymon1118 They have a pretty long list of domains, should all of them be matched or just `wp.pl` and `money.pl`?

**Comment by szymon1118** [comment] 2017-02-07 23:18
@X01X012013 I think script should work similarly for other domains but i'm not sure. Maybe @xxcriticxx make further tests because I rarely visit these websites. If I found any issues I will report.

**Comment by X01X012013** [comment] 2017-02-07 23:33
@szymon1118 I tried that Userscript, doesn't seem to work. I'll add all the domains in, the player patching routine shouldn't break anything. Let me know if it does.

**Comment by xxcriticxx** [comment] 2017-02-08 00:34
@szymon1118 i am in usa so i get geo lock on some videos 

@X01X012013 can you fix or patch that code that @MajkiIT put on his website? also wp provides videos for many different websites.

**Comment by X01X012013** [comment] 2017-02-08 01:35
@xxcriticxx 
I don't want to add Geo Lock breaking into AdBlock Protector. And I have no clue what is the thought process behind that Userscript. I mean I know what it does, but I don't know why it tried to do those things. 

Check this list for domains related to `wp.pl`. 
https://github.com/X01X012013/AdBlockProtector/blob/gh-pages/Related%20Domains.md
If you mean videos on "external" websites, then I will need to know which website does that and list them one by one. I can't make it generic since chances are it will break more than it fixes.

**Comment by xxcriticxx** [comment] 2017-02-08 02:25
@X01X012013 good start would be this list of domains from @F4z

```
http://biztok.pl
http://wp.tv
http://kafeteria.tv
http://kafeteria.pl
http://wrzuta.pl
http://pudelek.tv
http://komediowo.pl
http://sfora.pl
http://autokrata.pl
http://wawalove.pl
http://hotmoney.pl
http://snobka.pl
http://money.pl
http://abczdrowie.pl
http://gadzetomania.pl
http://autokult.pl
http://komorkomania.pl
```

**Comment by X01X012013** [comment] 2017-02-08 02:38
@xxcriticxx I think all those are already included.

**Comment by xxcriticxx** [comment] 2017-02-08 02:56
@X01X012013 i will dig around maybe i Find some more

**Comment by MajkiIT** [comment] 2017-02-08 07:25
All wp sites.

1. abczdrowie.pl
2. autokrata.pl
3. autokult.pl
4. biztok.pl
5. gadzetomania.pl
6. hotmoney.pl
7. kafeteria.pl
8. kafeteria.tv
9. komediowo.pl
10. komorkomania.pl
11. money.pl
12. pudelek.tv
13. sfora.pl
14. snobka.pl
15. wawalove.pl
16. *.wp.pl
17. wp.tv
18. wrzuta.pl
19. pudelek.pl

**Comment by X01X012013** [comment] 2017-02-08 14:11
@MajkiIT Yes, all 19 are already included. Please check here for the list: 
https://github.com/X01X012013/AdBlockProtector/blob/gh-pages/Related%20Domains.md

**Comment by xxcriticxx** [comment] 2017-02-08 16:06
got couple ad block today can someone test 

```
http://komorkomania.pl/34194,jak-wydluzyc-czas-pracy-telefonu-na-baterii
http://sportowefakty.wp.pl/sportowybar/664944/szpilka-trenowal-jak-rocky-balboa-jego-film-wzbudza-jednak-kontrowersje
http://wawalove.pl/Jest-sledztwo-ws-przyjecia-korzysci-majatkowej-przez-Hanne-Gronkiewicz-Waltz-lub-jej-zastepce-a25560
```

**Comment by X01X012013** [comment] 2017-02-08 17:35
@xxcriticxx I'll fix it

Note: load jQuery + hide block screen with List

**Comment by MajkiIT** [comment] 2017-02-08 18:02
@X01X012013 all domains are OK.

**Comment by xxcriticxx** [comment] 2017-02-08 18:08
@X01X012013 i have both list and script and i still get ad block msg

**Comment by X01X012013** [comment] 2017-02-08 19:02
@xxcriticxx I'll fix it, soon... Not done yet...

**Comment by X01X012013** [comment] 2017-02-08 21:38
@xxcriticxx This is partially patched in script 5.2 and list 5.2. The block screen is removed, the video is not really working, I'll fix it later.

**Comment by szymon1118** [comment] 2017-02-09 22:16
@X01X012013 OK so after more exploring WP websites I found that you can grab `mid` also with above 3 methods:

- Grabbing from inline script which is usually located above or below player DIV (this is a problematic method because you don't know for which player it exactly is):
```javascript
// <![CDATA[
var player = new WP.player({
url: 'http://get.wp.tv/?mid=1996815&ast=yes&s=1',
width:660,
height:450,
screenshot: '',
title : '',
});
// ]]>
```
...but maybe it would be useful if other methods fail.

- From cookie called `WPClipsShown` but I didn't figured yet in which order they are stored.
<details> 
  <summary>Picture related</summary>
 
![image](https://cloud.githubusercontent.com/assets/6980624/22805275/0774a68e-ef1d-11e6-876c-74334b379791.png)

</details>


- And the last method (I think the best because it should work on more websites than current method):

**Comment by szymon1118** [comment] 2017-02-09 22:27
@X01X012013 OK so after more exploring WP websites I found that you can grab `mid` also with above 3 methods:

- Grabbing from inline script which is usually located above or below player DIV (this is a problematic method because you don't know for which player it exactly is):
```javascript
// <![CDATA[
var player = new WP.player({
url: 'http://get.wp.tv/?mid=1996815&ast=yes&s=1',
width:660,
height:450,
screenshot: '',
title : '',
});
// ]]>
```
...but maybe it would be useful if other methods fail.
<br />

- From cookie called `WPClipsShown` but I didn't figure out yet in which order they are stored.
<details> 
  <summary>Picture related</summary>
 
![image](https://cloud.githubusercontent.com/assets/6980624/22805275/0774a68e-ef1d-11e6-876c-74334b379791.png)

</details>
<br /><br />

- And the last method (I think the best because it should work on more websites than current method):
`console.log(WP.player.list[0].p.url);` - `list[0]` is the first player from the top.

**Comment by X01X012013** [comment] 2017-02-10 01:24
@szymon1118 
OK nice. The 3rd method looks pretty promising, I'll have a look in a few days (after mid terms). 

In meantime, can you test RAM usage of 3~4 tabs open? And CPU usage when not playing any video? We may need to do some optimization to the main loop. (No ticking when is a background tab)

**Comment by szymon1118** [comment] 2017-02-10 16:10
RAM usage of 4 tabs with one playback video (I had only MBAM, f.lux and NVIDIA agent in background):
<details> 
  <summary>Here</summary>
   
![ram_new](https://cloud.githubusercontent.com/assets/6980624/22833661/09579646-efb3-11e6-90c1-bd612703f116.JPG)

</details><br />
CPU usage of 4 tabs without playback is about 0-5% sometimes jumps to 10% so I think it's not bad.
<br /><br />
Let me know if it is what did you mean.

**Comment by X01X012013** [comment] 2017-02-10 16:58
@szymon1118 
Yes, this is what I meant, but can you tell me: 
1. How much RAM does the browser uses? 
2. What is your CPU? You can check it in Device Manager, under Processors. 
![image](https://cloud.githubusercontent.com/assets/7283682/22835867/73952a28-ef77-11e6-9bb1-abc4a8eb4d68.png)

**Comment by szymon1118** [comment] 2017-02-10 17:46
@X01X012013 

<p>
1. I'm posting browser RAM usage with all of my daily driver extensions (about 600-700 MB):
<details>

![image](https://cloud.githubusercontent.com/assets/6980624/22836895/979d6c18-efbe-11e6-88a3-891a668ac66b.png)

</details><br />
2. CPU: Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz, 2931 MHz (1st gen, 4 cores).
</p>

**Comment by X01X012013** [comment] 2017-02-10 18:31
@szymon1118 The RAM usage looks pretty reasonable, I'll make some optimizations to CPU side and see how much that help.

**Comment by xxcriticxx** [comment] 2017-02-10 20:34
@X01X012013 i am on i5-4590S CPU @ 3.00GHz regular website 10 tabs open 4% cpu and about 725mb of ram. i open few tabs of wp.pl i jump up to 20% cpu and about 2gb of ram

**Comment by X01X012013** [comment] 2017-02-10 21:24
@xxcriticxx How many is a few more, if it's 10 more then that's reasonable. It's really hard for me to optimize the RAM usage, and I don't think it's needed, I can fix CPU usage this weekend.

**Comment by xxcriticxx** [comment] 2017-02-10 21:29
yep lets call it 15 tabs :)

**Comment by X01X012013** [comment] 2017-02-10 21:32
It's about 130MB per tab, still reasonable considering some pages have multiple videos.

**Comment by xxcriticxx** [comment] 2017-02-10 21:33
ok lets close this issue

**Comment by X01X012013** [comment] 2017-02-10 21:38
We still need to fix `sportowefakty.wp.pl`.

**Comment by xxcriticxx** [comment] 2017-02-10 21:40
yes i know i just found more ad block msg there 

test url

`http://sportowefakty.wp.pl/sportowybar/665412/wyszlo-jak-zawsze-trener-lapin-pokazal-szpilce-swoja-wyzszosc`

**Comment by X01X012013** [comment] 2017-02-10 21:55
@xxcriticxx 
I couldn't reproduce it, a screenshot? 

Also, please don't put links inside `code`.

**Comment by xxcriticxx** [comment] 2017-02-10 22:00
Some projects want them non clickable that's why I put them in code

**Comment by xxcriticxx** [comment] 2017-02-10 22:25
![capture](https://cloud.githubusercontent.com/assets/15007183/22846509/de19bfe2-efb5-11e6-94bd-1d3807939652.PNG)

full error log

http://pastebin.com/raw/xNxLNAgL

**Comment by X01X012013** [comment] 2017-02-10 22:39
@xxcriticxx Oh, you mean the block screen on the video, yes, we were having some issues grabbing `mid` for this subdomain, I'll fix it this weekend.

**Comment by xxcriticxx** [comment] 2017-02-10 22:40
ok

**Comment by X01X012013** [comment] 2017-02-11 17:42
Hi guys, this is fixed in Script 5.9, have a look and let me know how it goes.

**Comment by szymon1118** [comment] 2017-02-11 20:02
@X01X012013 I found issues on the following web pages:

- http://komediowo.pl/title,Tak-powstaja-portrety-malowane-kawa,vid,17879948,wideo.html?smpjqticaid=6189bd

- http://dom.wp.pl/wiadomosc_wideo.html?kat=1036235&title=Jak-pomiescic-ogromna-rodzine-w-jednym-domu&wid=18686310&smqbzticaid=1189bd

- http://moto.wp.pl/czy-plastikowe-opaski-na-kola-sa-skuteczniejsze-od-lancuchow-6088001547175041a

**Comment by X01X012013** [comment] 2017-02-11 20:37
@szymon1118 
These websites are patched in Script 5.11
Additionally, the Userscript will stop requesting JSON if there are 5 consecutive parsing errors or 10 consecutive network errors.

**Comment by X01X012013** [comment] 2017-02-14 14:52
Since there is no update for a while, I assume that the fix worked.

**Closed by X01X012013** 2017-02-14 14:52 UTC
Labels: Fixed

**Comment by ghajini** [comment] 2017-07-22 09:29
@jspenguin2017 
https://pilot.wp.pl/tv
website ss=
http://prntscr.com/fyu6mp

console output=
http://prntscr.com/fyu6tj
http://prntscr.com/fyu6xa

**Comment by jspenguin2017** [comment] 2017-07-22 13:34
This will be handled in #416
