### ISSUE TITLE
money.pl, komorkomania.pl

### ISSUE THREAD

**Issue by szymon1118** [X01X012013/AdBlockProtector#70] opened 2017-02-26 20:59 UTC
Someone reported issues with these URLs:

- http://www.money.pl/gospodarka/wiadomosci/artykul/morawiecki-wojna-50-mld-nowy-lad-narkoman,182,0,2269878.html

- http://komorkomania.pl/34279,huawei-p10-i-p10-plus-oficjalnie

**Comment by X01X012013** [comment] 2017-02-26 21:11
Fixed in 6.58
They are changing the class of their divs to dodge replacement.

**Comment by szymon1118** [comment] 2017-02-26 21:25
Scrolling through 2nd website I found issue with this URL:

- http://komorkomania.pl/33992,lg-g5-vs-samsung-galaxy-s7-porownanie-szybkosci

**Comment by X01X012013** [comment] 2017-02-26 21:42
OK, fixed in 6.62.

**Comment by MajkiIT** [comment] 2017-02-28 09:11
@X01X012013 Unfortunately not working. 
@szymon1118 On your PC is OK?

**Comment by X01X012013** [comment] 2017-02-28 14:27
@MajkiIT Hi, it's highly possible that it does not work over the whole `wp.pl` network, please provide a link to the page that does not work.

**Comment by MajkiIT** [comment] 2017-02-28 14:33
@X01X012013 
For example here http://komorkomania.pl/33992,lg-g5-vs-samsung-galaxy-s7-porownanie-szybkosci

**Comment by X01X012013** [comment] 2017-02-28 16:31
@MajkiIT OK, the matcher is messed up again. I'll fix it.

**Comment by szymon1118** [comment] 2017-02-28 16:50
@MajkiIT Link that you have posted works for me. Look that every link consists more articles loaded dynamically by AJAX when you are scrolling down the page. Try to scroll down and keep looking for your browser address bar and as you can see it changes all the time.

**Comment by X01X012013** [comment] 2017-02-28 19:06
@szymon1118 
After looking into this, method 2 sometimes fails to grab the `mid`... The `<a>` element doesn't always have `href`... And method 1 doesn't seem to work neither... 
From debug log, I see that method 1 and 2 are getting different `mid`, what do we do in this case?

**Comment by szymon1118** [comment] 2017-02-28 20:26
@X01X012013 I know that 2nd method may have some problems and that is why I was looking for other methods. I don't know exactly why It doesn't work, maybe try to check if player ID `<div id="Player8"` is the same as `WP.player.list[0].id` and if not go to the next element and check. Sorry but I haven't any better idea now and I'm almost sure that 1 method is good but dynamically loaded articles maybe brake the order.

**Comment by X01X012013** [comment] 2017-02-28 21:50
@szymon1118 
Ouch, this is getting complex pretty fast... When I tested it a few days ago, I think it worked fine... Looks like they are changing how their websites work. I'll have a look at this when I have time.

**Comment by szymon1118** [comment] 2017-02-28 22:03
@X01X012013 Ok, no problem.

**Comment by X01X012013** [comment] 2017-03-02 02:41
I would need to re-design that section of the script, so this will take a while...

**Comment by X01X012013** [comment] 2017-03-03 22:05
Hey guys, after a few bug fixes, I think this should work now.

**Comment by X01X012013** [comment] 2017-03-08 14:38
Hum, it stopped working again on the last test link ( http://komorkomania.pl/33992,lg-g5-vs-samsung-galaxy-s7-porownanie-szybkosci )...

**Comment by ghajini** [comment] 2017-03-08 18:12
@X01X012013 ,would you mind to see which method adguard using to overcome this.....in adguard its working

**Comment by xxcriticxx** [comment] 2017-03-08 22:01
@X01X012013 still working for me in ver 6.87 or i may have it webbrowinsing history

**Comment by xxcriticxx** [comment] 2017-03-08 22:19
@X01X012013 right something is off am getting ad block from time to time 

test links with ad block:

http://fotoblogia.pl/10370,to-dramatyczne-zdjecie-fali-atakujacej-prom-bije-rekordy-w-internecie
http://komorkomania.pl/34345,android-o-funkcje

**Comment by ghajini** [comment] 2017-03-09 01:49
@xxcriticxx on these sites e.g komorkomania.pl
Scroll downwards to load more stories and videos and play them,you will get adblock notice......

**Comment by X01X012013** [comment] 2017-03-09 04:38
@xxcriticxx I can't reproduce on http://fotoblogia.pl/10370,to-dramatyczne-zdjecie-fali-atakujacej-prom-bije-rekordy-w-internecie 
The whole `komorkomania.pl` is misbehaving, I'm investigating the cause.

**Comment by xxcriticxx** [comment] 2017-03-09 11:50
@X01X012013 ok how do i check xhr cross origin?

**Comment by X01X012013** [comment] 2017-03-09 14:27
Tampermonkey dashboard -> Click AdBlock Protector -> Click Settings, then scroll down and check this section, make sure to not have entries in Blacklist. 
![image](https://cloud.githubusercontent.com/assets/7283682/23754311/c417ea08-0499-11e7-9eea-74b0830e6882.png)

**Comment by xxcriticxx** [comment] 2017-03-09 14:54
@X01X012013 my looks same as yours

**Comment by X01X012013** [comment] 2017-03-09 16:06
@xxcriticxx I don't really know why but your system seems to behave differently...

**Comment by X01X012013** [comment] 2017-03-09 16:28
@ghajini AdGuard for Windows? Or just the AdGuard extension? The Windows version is close source proprietary software...

**Comment by ghajini** [comment] 2017-03-09 16:36
adguard extension....
also on komorkomania.pl, fotoblogia.pl
your code works only for intial videos,if you scroll downwards and next story loads,it will show adblock notice for that video....
it means code not working if you scroll downwards on same page for next video???
would you look into it..why ur solution not working for next video on same page...it will be nice

**Comment by ghajini** [comment] 2017-03-09 17:28
they are using this

`abczdrowie.pl,autokrata.pl,autokult.pl,biztok.pl,gadzetomania.pl,hotmoney.pl,kafeteria.pl,kafeteria.tv,komediowo.pl,komorkomania.pl,money.pl,pudelek.tv,sfora.pl,snobka.pl,wawalove.pl,wp.pl,wp.tv,wrzuta.pl#%#(function(b){function a(){"advertisement"!=arguments[0]&&b.apply(window,arguments)}Object.defineProperties(window,{hasSentinel:{get:function(){return function(){return!1}},set:function(){}},addEventListener:{get:function(){return a},set:function(a){b=a}}})})(window.addEventListener);
`

**Comment by X01X012013** [comment] 2017-03-09 17:35
Notes for devs: 
https://github.com/search?q=org%3AAdguardTeam+komorkomania.pl&type=Code

**Comment by X01X012013** [comment] 2017-03-09 17:41
Notes for devs: 
```JavaScript
    a.cookie("ABCABC", "true");
    a.filter("addEventListener", /advertisement/);
    a.readOnly("hasSentinel", function () { return false; });
```

**Comment by X01X012013** [comment] 2017-03-09 18:10
Wow, that's a LOT simpler than I thought... Looks like things are working now. Thanks. 

@MajkiIT @szymon1118 @xxcriticxx Hey guys, let's test out this new solution (patched into 6.88) 😄

**Comment by MajkiIT** [comment] 2017-03-09 18:26
@X01X012013 Thanks.
I tested on 10 random pages and it's OK, but give us few days.

**Comment by xxcriticxx** [comment] 2017-03-09 22:07
> @xxcriticxx I don't really know why but your system seems to behave differently...

@X01X012013 is it because i'm white?

**Comment by X01X012013** [comment] 2017-03-09 22:44
@xxcriticxx Lol no, it's probably some configurations somewhere in your network.

**Comment by xxcriticxx** [comment] 2017-03-10 02:55
@X01X012013 i use multiple system different os different networks

**Comment by ghajini** [comment] 2017-03-10 13:37
@X01X012013 
on money.pl video is not loadind-endless loading,vvideo not playing
`http://www.money.pl/gielda/wiadomosci/artykul/fundusze-inwestycyjne-naplywy-luty-2017,31,0,2277663.html`
ublock origin 1.11.2, uBo extra

**Comment by X01X012013** [comment] 2017-03-10 14:29
@ghajini 
Is it like that for every page on `money.pl`?

**Comment by ghajini** [comment] 2017-03-10 14:33
yes it is like that....on all pages of `money.pl`....loading bar never ends and playback never starts.....

**Comment by xxcriticxx** [comment] 2017-03-10 15:04
@X01X012013 works for me with script 6.89 and list 6.27

![capture](https://cloud.githubusercontent.com/assets/15007183/23800075/e5d92be0-0578-11e7-9945-582981a2b860.PNG)

**Comment by xxcriticxx** [comment] 2017-03-10 15:05
this on fox 52.0

**Comment by X01X012013** [comment] 2017-03-10 16:12
Looks like the problem isn't consistent across the whole domain, how about adding a button to Tampermonkey that will activate the old fix when clicked?

**Comment by ghajini** [comment] 2017-03-10 16:47
@X01X012013 
https://www.dropbox.com/s/7sejpprmzru2fdc/2017-03-10_22-09-08.mp4?dl=0

**Comment by X01X012013** [comment] 2017-03-10 17:11
`money.pl` is fixed in 6.90, using the old solution. Tested on the test link above. 

Can someone figure out what AdGuard did?

**Comment by xxcriticxx** [comment] 2017-03-10 19:18
@X01X012013 you should ping/poke them they have github repository i think main filter guy is @Alex-302. Alex can we ask you for some assistance in this matter?

**Comment by Alex-302** [comment] 2017-03-10 19:35
@xxcriticxx hi
What question do you have?

**Comment by xxcriticxx** [comment] 2017-03-10 20:20
@Alex-302 what does adguard use to play money.pl and komorkomania.pl 

this what we use but our fix breaks from day to day 

> money.pl is fixed in 6.90, using the old solution. Tested on the test link above.

>Did someone figure out what else AdGuard did?
>Our implementation is:

    a.cookie("ABCABC", "true");
    a.filter("addEventListener", /advertisement/);
    a.readOnly("hasSentinel", function () { return false; });

**Comment by ghajini** [comment] 2017-03-14 15:52
@Alex-302 any inputs regarding adguard functioning with these websites

**Comment by Alex-302** [comment] 2017-03-14 16:03
> what does adguard use to play money.pl and komorkomania.pl

I see only this rule
```
abczdrowie.pl,autokrata.pl,autokult.pl,biztok.pl,gadzetomania.pl,hotmoney.pl,kafeteria.pl,kafeteria.tv,komediowo.pl,komorkomania.pl,money.pl,pudelek.tv,sfora.pl,snobka.pl,wawalove.pl,wp.pl,wp.tv,wrzuta.pl#%#(function(b){function a(){"advertisement"!=arguments[0]&&b.apply(window,arguments)}Object.defineProperties(window,{hasSentinel:{get:function(){return function(){return!1}},set:function(){}},addEventListener:{get:function(){return a},set:function(a){b=a}}})})(window.addEventListener);
```
It was made by @seanl-adg (our member)

**Comment by X01X012013** [comment] 2017-03-14 16:31
@Alex-302 So it patches `addEventListener` and add a read-only `hasSentinel` function, that's exactly what we did, but it doesn't work on `money.pl`.

**Comment by X01X012013** [comment] 2017-03-14 16:33
@Alex-302 We are currently using our old solution which replaces the players for `money.pl`.

**Comment by seanl-adg** [comment] 2017-03-16 08:52
Hi, first of all, I noticed that
>that's exactly what we did

isn't true. In your implementation, you are testing all arguments of `addEventListener` with `/advertisement/` broadly, whereas the rule in Adguard English filter tests only the first argument (event name) with `=="advertisement"` or equivalently, `/^advertisement$/`.

They are using `WPJSLib` which has a feature of detecting adblocker presence. Websites can use this feature, for example in `wp.pl`, when a video advert is blocked, they call `hasSentinel` to check if a user have adblocker enabled.

**Comment by X01X012013** [comment] 2017-03-16 13:33
@seanl-adg Thanks for pointing this out, I'll test it out.

**Comment by X01X012013** [comment] 2017-03-19 23:48
@seanl-adg I tried `/^advertisement$/`, it doesn't seem to change anything... We still have to use the old fix for 2 domains, namely `money.pl` and `parenting.pl`.

**Comment by X01X012013** [comment] 2017-03-26 14:58
It's been a while and there is no feedback, so I assume the fix is working well. I'll close this issue now, please let me know if there are any problems.

**Closed by X01X012013** 2017-03-26 14:58 UTC
Labels: Fixed
